services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:lts
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /volume1/docker/portainer:/data
    ports:
      - 9443:9443
#      - 8000:8000  # Remove if you do not intend to use Edge Agents
    environment:
      - TZ=Europe/Berlin

networks:
  default:
    name: portainer_network