# Flatpak Restore Script
# Generated on Sa 22. Nov 00:22:49 CET 2025
flatpak remote-add --if-not-exists --user "flathub" "https://dl.flathub.org/repo/" --title="Flathub"
flatpak remote-add --if-not-exists --user "appcenter" "https://flatpak.elementary.io/repo" --title="AppCenter"
flatpak remote-add --if-not-exists --user "cosmic" "https://apt.pop-os.org/cosmic/" --title="COSMIC"
flatpak remote-add --if-not-exists --user "fedora" "oci+https://registry.fedoraproject.org" --title="Fedora"
flatpak remote-add --if-not-exists --user "flathub" "https://dl.flathub.org/repo/" --title="Flathub"
flatpak remote-add --if-not-exists --user "flathub-beta" "https://dl.flathub.org/beta-repo/" --title="Flathub beta"
flatpak remote-add --if-not-exists --user "gnome-nightly" "https://nightly.gnome.org/repo/" --title="GNOME Nightly"
flatpak remote-add --if-not-exists --user "webkit-sdk" "http://software.igalia.com/webkit-sdk-repo/" --title="WebKit Developer SDK"
flatpak install --assumeyes --user flathub "at.ssh_mitm.server"
flatpak install --assumeyes --user flathub "at.ssh_mitm.server"
flatpak install --assumeyes --user flathub "best.ellie.StartupConfiguration"
flatpak install --assumeyes --user flathub-beta "com.bitwarden.desktop"
flatpak install --assumeyes --user flathub "com.bitwarden.desktop"
flatpak install --assumeyes --user flathub "com.calibre_ebook.calibre"
flatpak install --assumeyes --user flathub "com.calibre_ebook.calibre"
flatpak install --assumeyes --user flathub "com.github.IsmaelMartinez.teams_for_linux"
flatpak install --assumeyes --user flathub "com.github.IsmaelMartinez.teams_for_linux"
flatpak install --assumeyes --user flathub "com.jwestall.Forecast"
flatpak install --assumeyes --user flathub-beta "com.usebottles.bottles"
flatpak install --assumeyes --user flathub "com.usebottles.bottles"
flatpak install --assumeyes --user flathub "dev.edfloreshz.CosmicTweaks"
flatpak install --assumeyes --user flathub "fr.sgued.bodev"
flatpak install --assumeyes --user flathub "fr.sgued.bodev"
flatpak install --assumeyes --user flathub "io.github.cosmic_utils.Examine"
flatpak install --assumeyes --user flathub "io.github.flattool.Warehouse"
flatpak install --assumeyes --user flathub "net.portswigger.BurpSuite-Community"
flatpak install --assumeyes --user flathub "net.portswigger.BurpSuite-Community"
flatpak install --assumeyes --user flathub "org.gnome.baobab"
flatpak install --assumeyes --user flathub "org.gnupg.GPA"
