# Flatpak Restore Script
# Generated on Di 2. Dez 03:16:32 CET 2025
flatpak remote-add --if-not-exists --user "flathub" "https://dl.flathub.org/repo/" --title="Flathub"
flatpak remote-add --if-not-exists --user "appcenter" "https://flatpak.elementary.io/repo" --title="AppCenter"
flatpak remote-add --if-not-exists --user "cosmic" "https://apt.pop-os.org/cosmic/" --title="COSMIC"
flatpak remote-add --if-not-exists --user "fedora" "oci+https://registry.fedoraproject.org" --title="Fedora"
flatpak remote-add --if-not-exists --user "flathub" "https://dl.flathub.org/repo/" --title="Flathub"
flatpak remote-add --if-not-exists --user "gnome-nightly" "https://nightly.gnome.org/repo/" --title="GNOME Nightly"
flatpak remote-add --if-not-exists --user "webkit-sdk" "http://software.igalia.com/webkit-sdk-repo/" --title="WebKit Developer SDK"
flatpak install --assumeyes --user flathub "app.devsuite.Manuals"
flatpak install --assumeyes --user flathub "app.drey.Dialect"
flatpak install --assumeyes --user flathub "app.grayjay.Grayjay"
flatpak install --assumeyes --user flathub "ar.xjuan.Cambalache"
flatpak install --assumeyes --user flathub "best.ellie.StartupConfiguration"
flatpak install --assumeyes --user flathub "com.bktus.gpgfrontend"
flatpak install --assumeyes --user flathub "com.cassidyjames.butler"
flatpak install --assumeyes --user flathub "com.freerdp.FreeRDP"
flatpak install --assumeyes --user flathub "com.github.IsmaelMartinez.teams_for_linux"
flatpak install --assumeyes --user flathub "com.github.LongSoft.UEFITool"
flatpak install --assumeyes --user flathub "com.github.finefindus.eyedropper"
flatpak install --assumeyes --user flathub "com.github.iwalton3.jellyfin-media-player"
flatpak install --assumeyes --user flathub "com.github.marhkb.Pods"
flatpak install --assumeyes --user flathub "com.github.phase1geo.minder"
flatpak install --assumeyes --user flathub "com.github.tchx84.Flatseal"
flatpak install --assumeyes --user flathub "com.github.wwmm.easyeffects"
flatpak install --assumeyes --user flathub "com.google.EarthPro"
flatpak install --assumeyes --user flathub "com.jwestall.Forecast"
flatpak install --assumeyes --user flathub "com.ktechpit.torrhunt"
flatpak install --assumeyes --user flathub "com.mattjakeman.ExtensionManager"
flatpak install --assumeyes --user flathub "com.ml4w.dotfilesinstaller"
flatpak install --assumeyes --user flathub "com.openwall.John"
flatpak install --assumeyes --user flathub "com.ranfdev.DistroShelf"
flatpak install --assumeyes --user flathub "com.stremio.Stremio"
flatpak install --assumeyes --user flathub "com.system76.Popsicle"
flatpak install --assumeyes --user flathub "de.lernsoftware_filius.Filius"
flatpak install --assumeyes --user cosmic "dev.cappsy.CosmicExtAppletLogoMenu"
flatpak install --assumeyes --user flathub "dev.deedles.Trayscale"
flatpak install --assumeyes --user flathub "dev.heppen.webapps"
flatpak install --assumeyes --user flathub "io.appflowy.AppFlowy"
flatpak install --assumeyes --user flathub "io.github.BuddySirJava.SSH-Studio"
flatpak install --assumeyes --user flathub "io.github.brunofin.Cohesion"
flatpak install --assumeyes --user flathub "io.github.flattool.Warehouse"
flatpak install --assumeyes --user flathub "io.github.qwersyk.Newelle"
flatpak install --assumeyes --user flathub "io.github.realmazharhussain.GdmSettings"
flatpak install --assumeyes --user flathub "io.github.ronniedroid.concessio"
flatpak install --assumeyes --user flathub "io.github.theforceengine.tfe"
flatpak install --assumeyes --user flathub "io.github.vmkspv.netsleuth"
flatpak install --assumeyes --user flathub "io.github.zarestia_dev.rclone-manager"
flatpak install --assumeyes --user flathub "io.gitlab.adhami3310.Impression"
flatpak install --assumeyes --user flathub "it.fabiodistasio.AntaresSQL"
flatpak install --assumeyes --user flathub "it.mijorus.gearlever"
flatpak install --assumeyes --user flathub "me.iepure.devtoolbox"
flatpak install --assumeyes --user flathub "net.code_industry.MasterPDFEditor"
flatpak install --assumeyes --user flathub "net.portswigger.BurpSuite-Community"
flatpak install --assumeyes --user flathub "net.sourceforge.roccat.roccat-tools"
flatpak install --assumeyes --user flathub "org.bleachbit.BleachBit"
flatpak install --assumeyes --user flathub "org.cockpit_project.CockpitClient"
flatpak install --assumeyes --user flathub "org.fkoehler.KTailctl"
flatpak install --assumeyes --user flathub "org.freac.freac"
flatpak install --assumeyes --user flathub "org.freecad.FreeCAD"
flatpak install --assumeyes --user flathub "org.fritzing.Fritzing"
flatpak install --assumeyes --user flathub "org.gnome.Firmware"
flatpak install --assumeyes --user flathub "org.gnome.GHex"
flatpak install --assumeyes --user flathub "org.gnome.Snapshot"
flatpak install --assumeyes --user flathub "org.gnome.World.PikaBackup"
flatpak install --assumeyes --user flathub "org.gnome.baobab"
flatpak install --assumeyes --user flathub "org.gnome.dspy"
flatpak install --assumeyes --user flathub "org.gramps_project.Gramps"
flatpak install --assumeyes --user flathub "org.kde.kdenlive"
flatpak install --assumeyes --user flathub "org.kde.kgeotag"
flatpak install --assumeyes --user flathub "org.libreoffice.LibreOffice"
flatpak install --assumeyes --user flathub "org.librepcb.LibrePCB"
flatpak install --assumeyes --user flathub "org.virt_manager.virt-manager"
