# Flatpak Restore Script
# Generated on Mo 1. Dez 23:43:23 CET 2025
flatpak remote-add --if-not-exists --user "flathub" "https://dl.flathub.org/repo/" --title="Flathub"
flatpak remote-add --if-not-exists --user "appcenter" "https://flatpak.elementary.io/repo" --title="AppCenter"
flatpak remote-add --if-not-exists --user "cosmic" "https://apt.pop-os.org/cosmic/" --title="COSMIC"
# Import COSMIC GPG key and enable verification
__cosmic_keyfile="$(mktemp)"
curl -fsSL https://apt.pop-os.org/cosmic/cosmic.flatpakrepo | awk -F= '/^GPGKey=/{print $2}' | base64 -d > "$__cosmic_keyfile"
flatpak remote-modify cosmic --gpg-import="$__cosmic_keyfile"
rm -f "$__cosmic_keyfile"
flatpak remote-modify cosmic --gpg-verify
flatpak remote-add --if-not-exists --user "fedora" "oci+https://registry.fedoraproject.org" --title="Fedora"
flatpak remote-add --if-not-exists --user "flathub" "https://dl.flathub.org/repo/" --title="Flathub"
flatpak remote-add --if-not-exists --user "gnome-nightly" "https://nightly.gnome.org/repo/" --title="GNOME Nightly"
flatpak remote-add --if-not-exists --user "webkit-sdk" "http://software.igalia.com/webkit-sdk-repo/" --title="WebKit Developer SDK"
flatpak install --assumeyes --user flathub "best.ellie.StartupConfiguration"
flatpak install --assumeyes --user flathub "com.bktus.gpgfrontend"
flatpak install --assumeyes --user flathub "com.jwestall.Forecast"
flatpak install --assumeyes --user flathub "com.ktechpit.torrhunt"
flatpak install --assumeyes --user flathub "com.mattjakeman.ExtensionManager"
flatpak install --assumeyes --user flathub "dev.heppen.webapps"
flatpak install --assumeyes --user flathub "io.github.flattool.Warehouse"
flatpak install --assumeyes --user flathub "io.github.zarestia_dev.rclone-manager"
flatpak install --assumeyes --user flathub "io.gitlab.adhami3310.Impression"
flatpak install --assumeyes --user flathub "org.gnome.Firmware"
flatpak install --assumeyes --user flathub "org.libreoffice.LibreOffice"
flatpak install --assumeyes --user flathub "org.virt_manager.virt-manager"
