version: "3.8"

services:
  snipeit:
    image: snipe/snipe-it:latest
    container_name: snipeit
    restart: unless-stopped
    ports:
      - "5030:80"
    environment:
      # Core app
      APP_ENV: production
      APP_DEBUG: "false"
      APP_URL: "https://oliver-s.cloud/snipeit" # change to your public URL
      APP_TIMEZONE: "CET"
      APP_LOCALE: "de"
      # Generate and set a persistent APP_KEY (base64:...) before production
      # If left empty on first run, check container logs for a generated key and set it here.
      APP_KEY: ""
      # Database (Synology MariaDB 10 typically listens on 3307)
      DB_CONNECTION: mysql
      DB_HOST: "192.168.178.2" # replace with your real Synology IP/hostname
      DB_PORT: "3306"
      DB_DATABASE: "snipeit"
      DB_USERNAME: "snipeit"
      DB_PASSWORD: "changeMe"
      # Mail (optional; configure for password resets, notifications)
#      MAIL_DRIVER: smtp
#      MAIL_HOST: smtp.example.com
#      MAIL_PORT: "587"
#      MAIL_USERNAME: ""
#      MAIL_PASSWORD: ""
#      MAIL_ENCRYPTION: tls
#      MAIL_FROM_ADDR: "noreply@example.com"
#      MAIL_FROM_NAME: "Snipe-IT"
    volumes:
      - /volume1/docker/snipeit/data:/var/lib/snipeit