# Docker Compose file for LazyDocker
# UNTESTED
services:
  lazydocker:
    image: lazyteam/lazydocker:latest
    container_name: lazydocker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /volume1/docker/lazydocker:/.config/jesseduffield/lazydocker
    stdin_open: true
    tty: true
    restart: "no"